"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import re
import environ
import os
from datetime import timedelta
from corsheaders.defaults import default_headers


def parseTokenLifetime(value: str) -> timedelta:
    """
    Parse a lifetime string from .env into a timedelta.

    Supported formats: number + unit, with optional space.
    Units: m/min/mins, h/hour/hours, d/day/days.
    Examples: 15m, 1 h, 7d, 1 day, 30 mins
    """
    if not value or not value.strip():
        raise ValueError("JWT lifetime value cannot be empty")
    value = value.strip().lower()
    match = re.match(r"^(\d+)\s*([a-z]+)$", value)
    if not match:
        raise ValueError(
            f"Invalid JWT lifetime format: '{value}'. Use e.g. 15m, 1 h, 7 d"
        )
    num = int(match.group(1))
    unit = match.group(2)
    if unit in ("m", "min", "mins", "minute", "minutes"):
        return timedelta(minutes=num)
    if unit in ("h", "hour", "hours", "hr", "hrs"):
        return timedelta(hours=num)
    if unit in ("d", "day", "days"):
        return timedelta(days=num)
    raise ValueError(
        f"Unknown JWT lifetime unit: '{unit}'. Use m, h, or d (e.g. 15m, 1 h, 7 d)"
    )


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "rest_framework",
    "drf_spectacular",
    "oauth2_provider",
    "corsheaders",
    "debug_toolbar",
    "django_prometheus",
]


MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

INTERNAL_IPS = [
    "127.0.0.1",
]
CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]


CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
]
CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": 3600,
    "AUTHORIZATION_CODE_EXPIRE_SECONDS": 300,
    "REFRESH_TOKEN_EXPIRE_SECONDS": 86400,
    "SCOPES": {"read": "Read scope", "write": "Write scope"},
    "ALLOWED_GRANT_TYPES": [
        "client_credentials",
        "password",
        "authorization_code",
        "refresh_token",
    ],
}

WSGI_APPLICATION = "config.wsgi.application"

# ADD THIS LINE
AUTH_USER_MODEL = "users.User"
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# JWT lifetimes from .env (e.g. 15m, 1 h, 7 d). Defaults used if not set.
_jwt_access_lifetime = env(
    "JWT_ACCESS_TOKEN_LIFETIME",
    default="15m",
)
_jwt_refresh_lifetime = env(
    "JWT_REFRESH_TOKEN_LIFETIME",
    default="7d",
)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": parseTokenLifetime(_jwt_access_lifetime),
    "REFRESH_TOKEN_LIFETIME": parseTokenLifetime(_jwt_refresh_lifetime),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "GOP Python API",
    "DESCRIPTION": "API documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # 🔐 JWT support in Swagger
    "SECURITY": [
        {
            "bearerAuth": [],
        }
    ],
    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}
SPECTACULAR_SETTINGS["COMPONENT_SPLIT_REQUEST"] = True

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
LOGGING = {
    "version": 1,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}
